name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  IMAGE_NAME: fists-kotlin-cicd-app
  REGISTRY: registry.digitalocean.com/sa-container-registry-dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    
    - name: Git Checkout
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $REGISTRY/$IMAGE_NAME:${{ github.sha }}-${{ github.run_number }}
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}-${{ github.run_number }}
