name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  IMAGE_NAME: fists-kotlin-cicd-app
  IMAGE_TAG: $(echo $GITHUB_SHA | head -c7)-$(date +%s)
  REGISTRY: registry.digitalocean.com/sa-container-registry-dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:IMAGE_TAG
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Push image to Registry
      run: |
        doctl registry login
        docker tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME
        docker push $REGISTRY/$IMAGE_NAME
