name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  IMAGE_NAME: fists-kotlin-cicd-app
  IMAGE_TAG: $GITHUB_SHA-$(date +%s)
  REGISTRY: registry.digitalocean.com/sa-container-registry-dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2.1.0
      with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: |
        docker images
        echo $IMAGE_TAG
        docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$IMAGE_TAG
